use crate::extended_enum_other;

extended_enum_other!(Status, u8,
    Success => 0x00,
    UnknownCommand => 0x01,
    NotConnected => 0x02,
    Failed => 0x03,
    ConnectFailed => 0x04,
    AuthenticationFailed => 0x05,
    NotPaired => 0x06,
    NoResources => 0x07,
    Timeout => 0x08,
    AlreadyConnected => 0x09,
    Busy => 0x0a,
    Rejected => 0x0b,
    NotSupported => 0x0c,
    InvalidParameters => 0x0d,
    Disconnected => 0x0e,
    NotPowered => 0x0f,
    Cancelled => 0x10,
    InvalidIndex => 0x11,
    Rfkilled => 0x12,
    AlreadyPaired => 0x13,
    PermissionDenied => 0x14,
);
